### ISSUE TITLE
Fails to render distances with raster based maps

### ISSUE THREAD

**Issue by steveneal** [bravecow/mapbox-gl-controls#11]
The distances measured are not displayed when using a tile based map:

<img width="613" alt="Screenshot 2019-11-08 at 14 03 41" src="https://user-images.githubusercontent.com/342829/68499920-da289580-0230-11ea-8d76-7ccc30858de1.png">

The map style in the screenshot, is configured as follows:

 ```
       map.setStyle({
            "version": 8,
            "sources": {
                "nasa-tiles": {
                    "type": "raster",
                    "tiles": [
                        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.jpg"
                    ],
                    "tileSize": 256
                }
            },
            "layers": [{
                "id": "nasa-tiles",
                "type": "raster",
                "source": "nasa-tiles",
                "minzoom": 0,
                "maxzoom": 22
            }]
        });
```

**Comment by bravecow** [comment]
Your style doesn't have fonts:

https://codesandbox.io/s/recursing-jepsen-zsxdy?fontsize=14

```
Error: layers.controls-layer-symbol.layout.text-field: use of "text-field" requires a style "glyphs" property
```

https://docs.mapbox.com/mapbox-gl-js/style-spec/#root-glyphs

I suggest you to add a new layer (`addLayer`) on top of mapbox style, with raster source (`addSource`), not to define the whole new style.

Something like this one: https://github.com/mapbox/mapbox-gl-js/issues/3496

**Comment by steveneal** [comment]
Thanks for your feedback. I'll look into your suggestion.
