### ISSUE TITLE
Ruler tool: change default text render options

### ISSUE THREAD

**Issue by karataev** [bravecow/mapbox-gl-controls#14]
I have a map with dark background and ruler text labels are hardly readable.
![image](https://user-images.githubusercontent.com/12277086/74118221-1501e700-4bed-11ea-85ad-80a827f27012.png)
Is it possible to tweak default text settings? I want to change text color and maybe increase font size.
If I get it right, these options are hardcoded here:
https://github.com/bravecow/mapbox-gl-controls/blob/726b14196087362c5fa6b1004f428ee270d57fad/src/ruler/ruler.js#L109

Maybe I miss something and the possibility to change default text style settings exists without forking the project?

**Comment by bravecow** [comment]
Color options are added: https://github.com/bravecow/mapbox-gl-controls/commit/6e7754291fc278603c25fc0736ca73b14cc4d95e

**Comment by bravecow** [comment]
If you need to increase font size let me know I will add this option too.

**Comment by karataev** [comment]
Wow, this was super fast!
For my case I ended up making `secondaryColor` transparent and text readability is much better now.
![image](https://user-images.githubusercontent.com/12277086/74207340-cb2f0480-4cb1-11ea-88b6-582c95922882.png)

Thanks a lot for your feedback and the awesome plugin!
