### ISSUE TITLE
[Build] suggestion to use ship.js for automated releases

### ISSUE THREAD

**Issue by vinayakkulkarni** [bravecow/mapbox-gl-controls#16]
I get a notifications from dependabot regarding new update for mapbox-gl-controls but when I try and look at the releases section of this repository, I couldn't find any release notes or changelog of what's exactly updated in the new version.

One suggestion I'd like to provide is using [`ship.js`](https://github.com/algolia/shipjs) which will remove the pain of creating changelogs, pushing new builds to npm etc. as it'll automate those tasks & create a proper semver releases of this awesome package.

// just my 2 cents

**Comment by bravecow** [comment]
Hi. Sorry for confusion, I do release notes only for notable / braking changes.
I created release notes for latest release: https://github.com/bravecow/mapbox-gl-controls/releases/tag/1.6.2
Will consider `ship.js` to make it easier 👍

**Comment by bravecow** [comment]
Done with github release / github actions. Thanks for raising it up.
