### ISSUE TITLE
Style selectors aren't specific enough to override

### ISSUE THREAD

**Issue by foundryspatial-duncan** [bravecow/mapbox-gl-controls#19]
The mapbox-gl stylesheet uses selectors like this:
```css
.mapboxgl-ctrl-group button
```
and the mapbox-gl-controls package overrides them with the exact same selectors. This works in cases where the mapbox-gl stylesheet is included first, but if you have a Webpack project for example, where mapbox-gl included from a package, they might be in the wrong order.

Then you're stuck with this: 

![Screenshot from 2020-05-28 10-23-04](https://user-images.githubusercontent.com/13056053/83173767-3fa97a00-a0ce-11ea-9604-d5a967aafeaa.png)

The button width is still the native `25px` instead of `auto` from your override styles.

Would you consider adding an extra class name, like `.mapbox-gl-controls` to make your override selector more specific so it will work in all cases?

**Comment by foundryspatial-duncan** [comment]
For anyone experiencing this same problem, you can work around it by doing a nested scss import:
```scss
// import mapbox-gl-controls with some extra scope ("map-view")
.map-view {
    @import '~mapbox-gl-controls/theme';
}
```

**Comment by bravecow** [comment]
@foundryspatial-duncan Agree with you. Since you found a workaround, I will do it a little bit later.

**Comment by bravecow** [comment]
@foundryspatial-duncan I do not know if you are interested in this issue, but it should be fixed in v2
