### ISSUE TITLE
AroundControl removed?

### ISSUE THREAD

**Issue by vinayakkulkarni** [bravecow/mapbox-gl-controls#22]
Hey @bravecow,

Have you removed the AroundControl in v1.6.5 (3D Icon) which was present in v1.6.4?

Use-case:

```js
import AroundControl from 'mapbox-gl-controls/lib/around';
map.addControl(new AroundControl(), 'top-right')
```

**Comment by bravecow** [comment]
Hi. Yes: https://github.com/bravecow/mapbox-gl-controls/releases/tag/1.6.3

I got a lot of negative feedback about this control. Sorry for inconvenience.

**Comment by vinayakkulkarni** [comment]
:(
