### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by LucasManerich** [bravecow/mapbox-gl-controls#26]
I'm trying to use this in my project, is there any interest in supporting typescript?

**Comment by bravecow** [comment]
Hi. Yes, I will try to play with JSDoc => d.ts 

https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by MatthewDownsNR** [comment]
Bump

**Comment by bravecow** [comment]
@LucasManerich v2 is in ts, except styles almost no braking changes.
