### ISSUE TITLE
enable / disable a control programmatically  without displaying the button

### ISSUE THREAD

**Issue by inttyl** [bravecow/mapbox-gl-controls#27]
Hi @bravecow ,
    Is there a way to add a control to the map without diplaying the button and still be able to enable and disable the controls programmatically ?

Thanks

**Comment by bravecow** [comment]
Hi. All buttons trigger some mapbox actions, that you can call inside your code without this project. For example, zoom is `zoomIn` method: https://github.com/bravecow/mapbox-gl-controls/blob/master/src/zoom/zoom.js#L27 and style switching is `setStyle` method: https://github.com/bravecow/mapbox-gl-controls/blob/master/src/styles/styles.js#L41

Maybe I can help more if you clarify your question 🤷‍♀️

**Comment by inttyl** [comment]
Hi,
      I mean is it possible to programmatically enable and disable the ruler programmatically without clickng the button with mouse ?

**Comment by bravecow** [comment]
@inttyl 

Hi. Yes, you can do this:

```js
const rulerControl = new RulerControl();
map.addControl(rulerControl, 'bottom-right');
map.on('load', () => {
  rulerControl.measuringOn(); // activate
  // or
  rulerControl.measuringOn(); // de-activate
});
```

Whether it solves your problem? 🙃

**Comment by bravecow** [comment]
Buttons are still visible but you can hide them with CSS. Maybe in next version I will add such option (to not insert control buttons)

**Comment by inttyl** [comment]
@bravecow 
Thanks !
