### ISSUE TITLE
IControl methods made private.

### ISSUE THREAD

**Issue by tapczan1337** [bravecow/mapbox-gl-controls#28]
Hello,
I'm confused, methods onAdd and onRemove are currently private. Can't use controls as shown in examples.

https://github.com/bravecow/mapbox-gl-controls/blob/51a98b615a2fd9c88eac29506c4dc0ad4f334332/src/Base/Base.ts#L34

**Comment by bravecow** [comment]
@tapczan1337 https://codesandbox.io/s/serene-saha-3kzs6

fixed, thanks. v 2.2.0
