### ISSUE TITLE
enhance documentation?

### ISSUE THREAD

**Issue by tin6150** [bravecow/mapbox-gl-controls#3]
Howdy bravecow, 
Thanks for this repo.  The examples are pretty good and concisely shows what each control add which feature, but could you elaborate more on how one can use them in an existing html page containing a single map using mapbox gl js ?

For instance, I have tried to use hopefully the simpler "style" feature, tried to trim your example to just have that as an example, but have not been able to do so.  It would be nice if things are not wrapped by webpack.  Even after installing webpack and figuring out to edit docs.js, I was still got 
    exampleLocalization is not defined.  

 A single example page with plain html/js code for a single feature, listing all required tools/components, would be really helpful.

Much thanks!

**Comment by bravecow** [comment]
👋Thanks for feedback. Docs moved to `stackblitz.io`.

```html
<script src="./styles.js"></script>
```
Should export `StylesControl` to `window` too.
