### ISSUE TITLE
SVG URI with '#' no longer works

### ISSUE THREAD

**Issue by jeniljain29392** [bravecow/mapbox-gl-controls#6]
As of chrome 72 '#' signifies the end of a uri. https://www.chromestatus.com/feature/5656049583390720

**Comment by bravecow** [comment]
Please clarify what exactly doesn't work. Updated to latest Chrome and don't see any issue with svg background.

**Comment by jeniljain29392** [comment]
![image](https://user-images.githubusercontent.com/10376431/57050751-ef45bb80-6c32-11e9-8976-75268897edae.png)
I don't know for me the buttons don't have any SVG. But if I change the 
> fill="#232323"

to

> fill="%23232323"

the SVG appears inside the button.

![image](https://user-images.githubusercontent.com/10376431/57050917-ab9f8180-6c33-11e9-8020-9a4b7352f00d.png)

**Comment by bravecow** [comment]
will fix it 👍

**Comment by bravecow** [comment]
Strange. theme.css doesn't have `#` in svg fill:

https://github.com/bravecow/mapbox-gl-controls/blob/master/theme.css#L45-L51

**Comment by jeniljain29392** [comment]
I am using the npm module https://www.npmjs.com/package/mapbox-gl-controls
and the mapbox-gl-controls.css file has `#`

```
<style src='mapbox-gl-controls/src/mapbox-gl-controls.css'> </style>
```
```
.mapboxgl-ctrl-zoom button:first-child {
    border-radius: 2px 2px 0 0;
    background-image: url('data:image/svg+xml;utf8,<svg fill="#232323" viewBox="0 0 24 24" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/><path d="M0 0h24v24H0z" fill="none"/></svg>');
}
.mapboxgl-ctrl-zoom button:last-child {
    border: none;
    border-radius: 0 0 2px 2px;
    background-image: url('data:image/svg+xml;utf8,<svg fill="#232323" viewBox="0 0 24 24" width="20" xmlns="http://www.w3.org/2000/svg"><path d="M19 13H5v-2h14v2z"/><path d="M0 0h24v24H0z" fill="none"/></svg>');
}
```

**Comment by bravecow** [comment]
@jeniljain29392 looks like you are using old version. v 1.0 have theme.css instead of mapbox-gl-controls.css

**Comment by jeniljain29392** [comment]
Thanks @bravecow.
