### ISSUE TITLE
Ruler to display different units of measure

### ISSUE THREAD

**Issue by steveneal** [bravecow/mapbox-gl-controls#8]
I really like your ruler but need something to measure miles and nautical miles with. Would you be happy for me to create a fork and develop this or is it something that you could add more quickly yourself?

**Comment by bravecow** [comment]
Hi. Thanks. We can do it easy for just `miles` with `@turf/distance` options:
https://github.com/Turfjs/turf/tree/master/packages/turf-distance

So `kilometers` are `miles`, and what do you expect to be `meters` (if `miles < 1`)? Or just `0.1 mi` so on?

**Comment by steveneal** [comment]
For my purposes thenth's of miles would be perfect, but I need to show nautical miles, not regular miles. 

How about allowing a function to be passed as an option to the Ruler constructor that would allow any conversion and formatting of the kilometer value to be performed?

For the existing kilometers this would look like (and could default to) : 

new Ruler({
    format: function(sum) {
        if (sum < 1) {
            return `${(sum * 1000).toFixed()} m`;
        }
        return `${sum.toFixed(2)} km`;
    }
});

It would be trivial for a user to convert the kilometer 'sum' argument to miles/nautical miles/feet/fathoms or any other measure of distance.

**Comment by bravecow** [comment]
Will do 👍🏿

**Comment by bravecow** [comment]
Please try new version: https://github.com/bravecow/mapbox-gl-controls/releases/tag/1.2.3

Example is here: https://bravecow.github.io/mapbox-gl-controls/

Now you can change `units` and label for it. Or keep default `units` and convert them using `labelFormat`.

**Comment by steveneal** [comment]
Fantastic. Thanks for your quick response! :)))
