### ISSUE TITLE
The StylesControl sample in README need a key "styles" on array parameter?

### ISSUE THREAD

**Issue by lripardo** [bravecow/mapbox-gl-controls#9]
Code in README:
`import StylesControl from 'mapbox-gl-controls/lib/styles';

// with default styles:
map.addControl(new StylesControl(), 'top-left');

// with custom styles:
map.addControl(new StylesControl([
  {
    label: 'Streets',
    styleName: 'Mapbox Streets',
    styleUrl: 'mapbox://styles/mapbox/streets-v9',
  }, {
    label: 'Satellite',
    styleName: 'Satellite',
    styleUrl: 'mapbox://styles/mapbox/satellite-v9',
  },
]), 'top-left');`

Fixed:
`import StylesControl from 'mapbox-gl-controls/lib/styles';

// with default styles:
map.addControl(new StylesControl(), 'top-left');

// with custom styles:
map.addControl(new StylesControl({
styles: [
  {
    label: 'Streets',
    styleName: 'Mapbox Streets',
    styleUrl: 'mapbox://styles/mapbox/streets-v9',
  }, {
    label: 'Satellite',
    styleName: 'Satellite',
    styleUrl: 'mapbox://styles/mapbox/satellite-v9',
  },
]
}), 'top-left');`

**Comment by bravecow** [comment]
@lripardo 

https://github.com/bravecow/mapbox-gl-controls/commit/50c5b3c9f1b8cfefdf4e35ea1a57ebc59523ce4c#diff-04c6e90faac2675aa89e2176d2eec7d8

Fixed, thanks.
